USE QUANLYXOSO;
--CHITIETKETQUAXOSO_INSERT
CREATE PROCEDURE CHITIETKETQUAXOSO_INSERT @p_MAKETQUAXOSO VARCHAR(15)    = NULL,
								  @p_MAGIAITHUONG VARCHAR(15)    = NULL,
								  @p_VE           NVARCHAR(1000) = NULL
AS
    BEGIN TRANSACTION;
	   INSERT INTO CHITIETKETQUAXOSO
	   (MAKETQUAXOSO,
	    MAGIAITHUONG,
	    VE
	   )
	   VALUES
	   (@p_MAKETQUAXOSO,
	    @p_MAGIAITHUONG,
	    @p_VE
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--CHITIETKETQUAXOSO_DELETE
CREATE PROCEDURE CHITIETKETQUAXOSO_DELETEBYMAKETQUAXOSO @p_MAKETQUAXOSO VARCHAR(15) = NULL
AS
    BEGIN TRANSACTION;
	   DELETE FROM CHITIETKETQUAXOSO
	   WHERE MAKETQUAXOSO = @p_MAKETQUAXOSO;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--CHITIETKETQUAXOSO_SERACHBYNGAYMOTHUONGMALOAIVE
CREATE PROCEDURE CHITIETKETQUAXOSO_SEARCHBYNGAYMOTHUONGMALOAIVE @p_NGAYMOTHUONG DATE        = NULL,
												    @p_MALOAIVE     VARCHAR(15) = NULL
AS
	SELECT chitietketquaxoso.MAGIAITHUONG,
		  giaithuong.TENGIAITHUONG,
		  chitietketquaxoso.VE
	FROM KETQUAXOSO AS ketquaxoso,
		GIAITHUONG AS giaithuong,
		CHITIETKETQUAXOSO AS chitietketquaxoso
	WHERE ketquaxoso.NGAYMOTHUONG = @p_NGAYMOTHUONG
		 AND ketquaxoso.MALOAIVE = @p_MALOAIVE
		 AND ketquaxoso.MAKETQUAXOSO = chitietketquaxoso.MAKETQUAXOSO
		 AND giaithuong.MAGIAITHUONG = chitietketquaxoso.MAGIAITHUONG;
GO