USE QUANLYXOSO;

CREATE PROCEDURE CHITIETDOTPHATHANH_INSERT @p_MACHITIETDOTPHATHANH  VARCHAR(15)   = NULL OUTPUT,
							 @p_MADOTPHATHANH VARCHAR(15) = NULL,
							 @p_MADOITAC VARCHAR(15) = NULL,
							 @p_MALOAIVE VARCHAR(15) = NULL,
							 @p_SOVEPHATHANH INT = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'CTDPH',
		   @p_MACHITIETDOTPHATHANH OUTPUT;
	   IF @p_MACHITIETDOTPHATHANH = ''
		 OR @p_MACHITIETDOTPHATHANH IS NULL
		  GOTO ABORT;
	   INSERT INTO CHITIETDOTPHATHANH
	   (
	    MACHITIETDOTPHATHANH,
	    MADOTPHATHANH,
	    MADOITAC,
	    MALOAIVE,
		SOVEPHATHANH
	   )
	   VALUES
	   (@p_MACHITIETDOTPHATHANH,
	    @p_MADOTPHATHANH,
	    @p_MADOITAC,
	    @p_MALOAIVE,
		@p_SOVEPHATHANH
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MACHITIETDOTPHATHANH;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO

CREATE PROCEDURE CHITIETDOTPHATHANH_UPDATE @p_MACHITIETDOTPHATHANH  VARCHAR(15)   = NULL OUTPUT,
							 @p_MADOTPHATHANH VARCHAR(15) = NULL,
							 @p_MADOITAC VARCHAR(15) = NULL,
							 @p_MALOAIVE VARCHAR(15) = NULL,
							 @p_SOVEPHATHANH INT = NULL
AS
    BEGIN TRANSACTION;
	   UPDATE CHITIETDOTPHATHANH
		SET
		MADOTPHATHANH  = @p_MADOTPHATHANH ,
	    MADOITAC = @p_MADOITAC,
	    MALOAIVE = @p_MALOAIVE,
		SOVEPHATHANH = @p_SOVEPHATHANH

	   WHERE MACHITIETDOTPHATHANH = @p_MACHITIETDOTPHATHANH;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO

CREATE PROCEDURE CHITIETDOTPHATHANH_DELETE @p_MACHITIETDOTPHATHANH VARCHAR(15) = NULL
AS
	DELETE FROM CHITIETDOTPHATHANH
	WHERE MACHITIETDOTPHATHANH = @p_MACHITIETDOTPHATHANH;
GO
