USE QUANLYXOSO;
--CHITIETKETQUAXOSO_INSERT
CREATE PROCEDURE CHITIETKETQUAXOSO_INSERT @p_MAKETQUAXOSO VARCHAR(15) = NULL,
							@p_MAGIAITHUONG VARCHAR(15) = NULL,
							@p_VE     NVARCHAR(1000) = NULL
AS
    BEGIN TRANSACTION;
	   INSERT INTO CHITIETKETQUAXOSO
	   (MAKETQUAXOSO,
	    MAGIAITHUONG,
	    VE
	   )
	   VALUES
	   (@p_MAKETQUAXOSO,
	    @p_MAGIAITHUONG,
	    @p_VE
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--CHITIETKETQUAXOSO_DELETE
CREATE PROCEDURE CHITIETKETQUAXOSO_DELETEBYMAKETQUAXOSO @p_MAKETQUAXOSO VARCHAR(15) = NULL
AS
    BEGIN TRANSACTION;
	   DELETE FROM CHITIETKETQUAXOSO
	   WHERE MAKETQUAXOSO = @p_MAKETQUAXOSO;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO