USE QUANLYXOSO;
--COCAUCOCAUGIAITHUONG_INSERT
CREATE PROCEDURE COCAUGIAITHUONG_INSERT @p_MACOCAUGIAITHUONG VARCHAR(15) = NULL OUTPUT,
									@p_NGAYLAP                DATETIME    = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'CCGT',
		   @p_MACOCAUGIAITHUONG OUTPUT;
	   IF @p_MACOCAUGIAITHUONG = ''
		 OR @p_MACOCAUGIAITHUONG IS NULL
		  GOTO ABORT;
	   INSERT INTO COCAUGIAITHUONG
	   (MACOCAUGIAITHUONG,
	    NGAYLAP
	   )
	   VALUES
	   (@p_MACOCAUGIAITHUONG,
	    @p_NGAYLAP
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MACOCAUGIAITHUONG;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--COCAUGIAITHUONG_UPDATE
CREATE PROCEDURE COCAUGIAITHUONG_UPDATE @p_MACOCAUGIAITHUONG VARCHAR(15) = NULL,
								@p_NGAYLAP           DATETIME    = NULL
AS
	UPDATE COCAUGIAITHUONG
	  SET
		 NGAYLAP = @p_NGAYLAP
	WHERE MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG;
GO
--COCAUGIAITHUONG_DELETE
CREATE PROCEDURE COCAUGIAITHUONG_DELETE @p_MACOCAUGIAITHUONG VARCHAR(15) = NULL
AS
    BEGIN TRANSACTION;
	   DELETE FROM GIAITHUONG
	   WHERE MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG;
	   DELETE FROM COCAUGIAITHUONG
	   WHERE MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--COCAUGIAITHUONG_SEARCHBYMACOCAUGIAITHUONG
CREATE PROCEDURE COCAUGIAITHUONG_SEARCHBYMACOCAUGIAITHUONG @p_MACOCAUGIAITHUONG VARCHAR(15) = NULL
AS
	SELECT *
	FROM COCAUGIAITHUONG
	WHERE MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG;
GO