USE QUANLYXOSO;
--DOTPHATHANH_INSERT
CREATE PROCEDURE DOTPHATHANH_INSERT @p_MADOTPHATHANH  VARCHAR(15)   = NULL OUTPUT,
							 @p_TENDOTPHATHANH NVARCHAR(500) = NULL,
							 @p_NGAYLAP        DATETIME      = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'DPH',
		   @p_MADOTPHATHANH OUTPUT;
	   IF @p_MADOTPHATHANH = ''
		 OR @p_MADOTPHATHANH IS NULL
		  GOTO ABORT;
	   INSERT INTO DOTPHATHANH
	   (MADOTPHATHANH,
	    TENDOTPHATHANH,
	    NGAYLAP
	   )
	   VALUES
	   (@p_MADOTPHATHANH,
	    @p_TENDOTPHATHANH,
	    @p_NGAYLAP
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MADOTPHATHANH;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--DOTPHATHANH_UPDATE
CREATE PROCEDURE DOTPHATHANH_UPDATE @p_MADOTPHATHANH  VARCHAR(15)   = NULL,
							 @p_TENDOTPHATHANH NVARCHAR(500) = NULL,
							 @p_NGAYLAP        DATETIME      = NULL
AS
    BEGIN TRANSACTION;
	   UPDATE DOTPHATHANH
		SET
		    TENDOTPHATHANH = @p_TENDOTPHATHANH,
		    NGAYLAP = @p_NGAYLAP
	   WHERE MADOTPHATHANH = @p_MADOTPHATHANH;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--DOTPHATHANH_DELETE
CREATE PROCEDURE DOTPHATHANH_DELETE @p_MADOTPHATHANH VARCHAR(15) = NULL
AS
	DELETE FROM DOTPHATHANH
	WHERE MADOTPHATHANH = @p_MADOTPHATHANH;
GO
--LOAIVE_SEARCHBYDOTPHATHANH
CREATE PROCEDURE LOAIVE_SEARCHBYMADOTPHATHANH @p_MADOTPHATHANH VARCHAR(15) = NULL
AS
	SELECT *
	FROM DOTPHATHANH
	WHERE MADOTPHATHANH = @p_MADOTPHATHANH;
GO