USE QUANLYXOSO;
--GIAITHUONG_INSERT
CREATE PROCEDURE GIAITHUONG_INSERT @p_MAGIAITHUONG      VARCHAR(15)   = NULL OUTPUT,
							@p_TENGIAITHUONG     NVARCHAR(500) = NULL,
							@p_MACOCAUGIAITHUONG VARCHAR(15)   = NULL,
							@p_TRIGIA            MONEY         = NULL,
							@p_SOLUONG           INT           = NULL,
							@p_SOCHUSOTRUNG      INT           = NULL,
							@p_SOLANQUAY         INT           = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'GT',
		   @p_MAGIAITHUONG OUTPUT;
	   IF @p_MAGIAITHUONG = ''
		 OR @p_MAGIAITHUONG IS NULL
		  GOTO ABORT;
	   INSERT INTO GIAITHUONG
	   (MAGIAITHUONG,
	    TENGIAITHUONG,
	    MACOCAUGIAITHUONG,
	    TRIGIA,
	    SOLUONG,
	    SOCHUSOTRUNG,
	    SOLANQUAY
	   )
	   VALUES
	   (@p_MAGIAITHUONG,
	    @p_TENGIAITHUONG,
	    @p_MACOCAUGIAITHUONG,
	    @p_TRIGIA,
	    @p_SOLUONG,
	    @p_SOCHUSOTRUNG,
	    @p_SOLANQUAY
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MAGIAITHUONG;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--GIAITHUONG_UPDATE
CREATE PROCEDURE GIAITHUONG_UPDATE @p_MAGIAITHUONG      VARCHAR(15)   = NULL,
							@p_TENGIAITHUONG     NVARCHAR(500) = NULL,
							@p_MACOCAUGIAITHUONG VARCHAR(15)   = NULL,
							@p_TRIGIA            MONEY         = NULL,
							@p_SOLUONG           INT           = NULL,
							@p_SOCHUSOTRUNG      INT           = NULL,
							@p_SOLANQUAY         INT           = NULL
AS
	UPDATE GIAITHUONG
	  SET
		 TENGIAITHUONG = @p_TENGIAITHUONG,
		 MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG,
		 TRIGIA = @p_TRIGIA,
		 SOLUONG = @p_SOLUONG,
		 SOCHUSOTRUNG = @p_SOCHUSOTRUNG,
		 SOLANQUAY = @p_SOLANQUAY
	WHERE MAGIAITHUONG = @p_MAGIAITHUONG;
GO
--GIAITHUONG_DELETE
CREATE PROCEDURE GIAITHUONG_DELETE @p_MAGIAITHUONG VARCHAR(15) = NULL
AS
	DELETE
	FROM GIAITHUONG
	WHERE MAGIAITHUONG = @p_MAGIAITHUONG;
GO
--GIAITHUONG_SEARCHBYMACOCAUGIAITHUONG
CREATE PROCEDURE GIAITHUONG_SEARCHBYMACOCAUGIAITHUONG @p_MACOCAUGIAITHUONG VARCHAR(15) = NULL
AS
	SELECT *
	FROM GIAITHUONG
	WHERE MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG;
GO