USE QUANLYXOSO;
--KETQUAXOSO_INSERT
CREATE PROCEDURE KETQUAXOSO_INSERT @p_MAKETQUAXOSO VARCHAR(15) = NULL OUTPUT,
							@p_NGAYMOTHUONG DATE        = NULL,
							@p_MALOAIVE     VARCHAR(15) = NULL
AS
    BEGIN TRANSACTION;
	   IF(EXISTS
		(
		    SELECT *
		    FROM KETQUAXOSO
		    WHERE NGAYMOTHUONG = @p_NGAYMOTHUONG
				AND MALOAIVE = @p_MALOAIVE
		))
		  EXEC KETQUAXOSO_DELETEBYNGAYMOTHUONGMALOAIVE
			  @p_NGAYMOTHUONG,
			  @p_MALOAIVE;
	   EXEC GENCODE
		   'KQXS',
		   @p_MAKETQUAXOSO OUTPUT;
	   IF @p_MAKETQUAXOSO = ''
		 OR @p_MAKETQUAXOSO IS NULL
		  GOTO ABORT;
	   INSERT INTO KETQUAXOSO
	   (MAKETQUAXOSO,
	    NGAYMOTHUONG,
	    MALOAIVE
	   )
	   VALUES
	   (@p_MAKETQUAXOSO,
	    @p_NGAYMOTHUONG,
	    @p_MALOAIVE
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MAKETQUAXOSO;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--KETQUAXOSO_DELETE
CREATE PROCEDURE KETQUAXOSO_DELETEBYNGAYMOTHUONGMALOAIVE @p_NGAYMOTHUONG DATE        = NULL,
											  @p_MALOAIVE     VARCHAR(15) = NULL
AS
	DECLARE @l_MAKETQUAXOSO VARCHAR(15);
	SET @l_MAKETQUAXOSO =
	(
	    SELECT MAKETQUAXOSO
	    FROM KETQUAXOSO
	    WHERE NGAYMOTHUONG = @p_NGAYMOTHUONG
			AND MALOAIVE = @p_MALOAIVE
	);
	BEGIN TRANSACTION;
	EXEC CHITIETKETQUAXOSO_DELETEBYMAKETQUAXOSO
		@l_MAKETQUAXOSO;
	DELETE FROM KETQUAXOSO
	WHERE NGAYMOTHUONG = @p_NGAYMOTHUONG
		 AND MALOAIVE = @p_MALOAIVE;
	COMMIT TRANSACTION;
	RETURN '0';
	ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO