USE QUANLYXOSO;
--LOAIVE_INSERT
CREATE PROCEDURE LOAIVE_INSERT @p_MALOAIVE          VARCHAR(15)   = NULL OUTPUT,
						 @p_TENLOAIVE         NVARCHAR(500) = NULL,
						 @p_NGAYLAP           DATETIME      = NULL,
						 @p_MENHGIA           MONEY         = NULL,
						 @p_MADOITAC          VARCHAR(15)   = NULL,
						 @p_MACOCAUGIAITHUONG VARCHAR(15)   = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'LV',
		   @p_MALOAIVE OUTPUT;
	   IF @p_MALOAIVE = ''
		 OR @p_MALOAIVE IS NULL
		  GOTO ABORT;
	   INSERT INTO LOAIVE
	   (MALOAIVE,
	    TENLOAIVE,
	    NGAYLAP,
	    MENHGIA,
	    MADOITAC,
	    MACOCAUGIAITHUONG
	   )
	   VALUES
	   (@p_MALOAIVE,
	    @p_TENLOAIVE,
	    @p_NGAYLAP,
	    @p_MENHGIA,
	    @p_MADOITAC,
	    @p_MACOCAUGIAITHUONG
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MALOAIVE;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--LOAIVE_UPDATE
CREATE PROCEDURE LOAIVE_UPDATE @p_MALOAIVE          VARCHAR(15)   = NULL,
						 @p_TENLOAIVE         NVARCHAR(500) = NULL,
						 @p_NGAYLAP           DATETIME      = NULL,
						 @p_MENHGIA           MONEY         = NULL,
						 @p_MADOITAC          VARCHAR(15)   = NULL,
						 @p_MACOCAUGIAITHUONG VARCHAR(15)   = NULL
AS
    BEGIN TRANSACTION;
	   UPDATE LOAIVE
		SET
		    TENLOAIVE = @p_TENLOAIVE,
		    NGAYLAP = @p_NGAYLAP,
		    MENHGIA = @p_MENHGIA,
		    MADOITAC = @p_MADOITAC,
		    MACOCAUGIAITHUONG = @p_MACOCAUGIAITHUONG
	   WHERE MALOAIVE = @p_MALOAIVE;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--LOAIVE_DELETE
CREATE PROCEDURE LOAIVE_DELETE @p_MALOAIVE VARCHAR(15) = NULL
AS
	DELETE
	FROM LOAIVE
	WHERE MALOAIVE = @p_MALOAIVE;
GO
--LOAIVE_SEARCHBYMALOAIVE
CREATE PROCEDURE LOAIVE_SEARCHBYMALOAIVE @p_MALOAIVE VARCHAR(15) = NULL
AS
	SELECT *
	FROM LOAIVE
	WHERE MALOAIVE = @p_MALOAIVE;