USE QUANLYXOSO;

CREATE PROCEDURE PHIEUTHU_INSERT	 @p_MAPHIEUTHU          VARCHAR(15)   = NULL OUTPUT,
									 @p_NGAYLAP             datetime = NULL,
									 @p_MADOITAC            VARCHAR(15) = NULL,
									 @p_MADOTPHATHANH       VARCHAR(15) = NULL,
									 @p_SOTIENTHU	        money = null
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'PT',
		   @p_MAPHIEUTHU OUTPUT;
	   IF @p_MAPHIEUTHU = ''
		 OR @p_MAPHIEUTHU IS NULL
		  GOTO ABORT;
	   INSERT INTO PHIEUTHU
	   (MAPHIEUTHU,
	    NGAYLAP,
	    MADOITAC,
	    MADOTPHATHANH,
		SOTIENTHU
	   )
	   VALUES
	   (@p_MAPHIEUTHU,
		@p_NGAYLAP,
		@p_MADOITAC,
		@p_MADOTPHATHANH,
		@p_SOTIENTHU
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MAPHIEUTHU;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO

CREATE PROCEDURE PHIEUTHU_UPDATE	 @p_MAPHIEUTHU          VARCHAR(15)   = NULL OUTPUT,
									 @p_NGAYLAP             datetime = NULL,
									 @p_MADOITAC            VARCHAR(15) = NULL,
									 @p_MADOTPHATHANH       VARCHAR(15) = NULL,
									 @p_SOTIENTHU	        money = null
AS
    BEGIN TRANSACTION;
	   UPDATE PHIEUTHU
		SET
	    NGAYLAP  =  @p_NGAYLAP,
	    MADOITAC =  @p_MADOITAC,
	    MADOTPHATHANH  =  @p_MADOTPHATHANH,
		SOTIENTHU  =  @p_SOTIENTHU
	   WHERE MAPHIEUTHU = @p_MAPHIEUTHU;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO

CREATE PROCEDURE PHIEUTHU_DELETE @p_MAPHIEUTHU VARCHAR(15) = NULL
AS
	DELETE
	FROM PHIEUTHU
	WHERE MAPHIEUTHU = @p_MAPHIEUTHU;
GO

CREATE PROCEDURE PHIEUTHU_SEARCHBYMAPHIEUTHU @p_MAPHIEUTHU VARCHAR(15) = NULL
AS
	SELECT *
	FROM PHIEUTHU
	WHERE MAPHIEUTHU = @p_MAPHIEUTHU;

