USE QUANLYXOSO;
--PHIEUTRAVE_INSERT
CREATE PROCEDURE PHIEUTRAVE_INSERT	 @p_MAPHIEUTRAVE           VARCHAR(15)   = NULL OUTPUT,
									 @p_NGAYLAP                  datetime = NULL,
									 @p_MADOITAC                 VARCHAR(15) = NULL,
									 @p_MADOTPHATHANH            VARCHAR(15) = NULL
AS
      INSERT INTO PHIEUTRAVE
	   (MAPHIEUTRAVE,
	    NGAYLAP,
	    MADOITAC,
	    MADOTPHATHANH
	   )
	   VALUES
	   ( @p_MAPHIEUTRAVE ,
		 @p_NGAYLAP ,
		 @p_MADOITAC ,
		 @p_MADOTPHATHANH
	   );
GO
--PHIEUTRAVE_UPDATE
CREATE PROCEDURE PHIEUTRAVE_UPDATE  @p_MAPHIEUTRAVE           VARCHAR(15)   = NULL OUTPUT,
									 @p_NGAYLAP                  datetime = NULL,
									 @p_MADOITAC                 VARCHAR(15) = NULL,
									 @p_MADOTPHATHANH            VARCHAR(15) = NULL
AS
    BEGIN TRANSACTION;
	   UPDATE PHIEUTRAVE
		SET
		    MAPHIEUTRAVE = @p_MAPHIEUTRAVE,
		    NGAYLAP = @p_NGAYLAP,
		    MADOITAC = @p_MADOITAC,
			MADOTPHATHANH = @P_MADOTPHATHANH
	   WHERE MAPHIEUTRAVE = @p_MAPHIEUTRAVE;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--PHIEUTRAVE_DELETE
CREATE PROCEDURE PHIEUTRAVE_DELETE @p_MAPHIEUTRAVE VARCHAR(15) = NULL
AS
	DELETE
	FROM PHIEUTRAVE
	WHERE MAPHIEUTRAVE = @p_MAPHIEUTRAVE;
GO
--PHIEUTRAVE_SEARCHBYMAPHIEUTRAVE
CREATE PROCEDURE PHIEUTRAVE_SEARCHBYMAPHIEUTRAVE @p_MAPHIEUTRAVE VARCHAR(15) = NULL
AS
	SELECT *
	FROM PHIEUTRAVE
	WHERE MAPHIEUTRAVE = @p_MAPHIEUTRAVE;
GO

--CHITIETPHIEUTRAVE_INSERT
CREATE PROCEDURE CHITIETPHIEUTRAVE_INSERT   @P_MAPHIEUTRAVE VARCHAR(15) = NULL,
											@P_MALOAIVE VARCHAR(15) = NULL,
											@p_SOLUONGTRA INT

	
AS
	   INSERT INTO CHITIETPHIEUTRAVE
	   (
	    MAPHIEUTRAVE,
	    MALOAIVE,
	    SOLUONGTRA
	   )
	   VALUES
	   ( 
		 @P_MAPHIEUTRAVE ,
		 @P_MALOAIVE ,
		 @p_SOLUONGTRA
	   );
GO