USE QUANLYXOSO;
--TAIKHOAN_INSERT
CREATE PROCEDURE TAIKHOAN_INSERT	 @p_MATAIKHOAN          VARCHAR(15)   = NULL OUTPUT,
									 @p_TENDANGNHAP         VARCHAR(30) = NULL,
									 @p_MATKHAU             VARCHAR(15) = NULL,
									 @p_QUYENHAN            VARCHAR(1) = NULL
AS
    BEGIN TRANSACTION;
	   EXEC GENCODE
		   'TK',
		   @p_MATAIKHOAN OUTPUT;
	   IF @p_MATAIKHOAN = ''
		 OR @p_MATAIKHOAN IS NULL
		  GOTO ABORT;
	   INSERT INTO TAIKHOAN
	   (MATAIKHOAN,
	    TENDANGNHAP,
	    MATKHAU,
	    QUYENHAN
	   )
	   VALUES
	   (@p_MATAIKHOAN,
		@p_TENDANGNHAP,
		@p_MATKHAU,
		@p_QUYENHAN
	   );
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   SELECT @p_MATAIKHOAN;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--TAIKHOAN_UPDATE
CREATE PROCEDURE TAIKHOAN_UPDATE	 @p_MATAIKHOAN          VARCHAR(15)   = NULL OUTPUT,
									 @p_TENDANGNHAP         VARCHAR(30) = NULL,
									 @p_MATKHAU             VARCHAR(15) = NULL,
									 @p_QUYENHAN            VARCHAR(1) = NULL
AS
    BEGIN TRANSACTION;
	   UPDATE TAIKHOAN
		SET
		    TENDANGNHAP = @p_TENDANGNHAP,
		    MATKHAU = @p_MATKHAU,
		    QUYENHAN = @p_QUYENHAN
	   WHERE MATAIKHOAN = @p_MATAIKHOAN;
	   IF @@Error <> 0
		  GOTO ABORT;
	   COMMIT TRANSACTION;
	   RETURN '0';
	   ABORT:
	BEGIN
	    ROLLBACK TRANSACTION;
	END;
GO
--TAIKHOAN_DELETE
CREATE PROCEDURE TAIKHOAN_DELETE @p_MATAIKHOAN VARCHAR(15) = NULL
AS
	DELETE
	FROM TAIKHOAN
	WHERE MATAIKHOAN = @p_MATAIKHOAN;
GO
--TAIKHOAN_SEARCHBYMATAIKHOAN
CREATE PROCEDURE TAIKHOAN_SEARCHBYMATAIKHOAN @p_MATAIKHOAN VARCHAR(15) = NULL
AS
	SELECT *
	FROM TAIKHOAN
	WHERE MATAIKHOAN = @p_MATAIKHOAN;
	--TAIKHOAN_SEARCHBYTENDANGNHAPMATKHAU
CREATE PROCEDURE TAIKHOAN_SEARCHBYTENDANGNHAPMATKHAU @p_TENDANGNHAP VARCHAR(30) = NULL,
													 @p_MATKHAU VARCHAR(15) = NULL
AS
	SELECT *
	FROM TAIKHOAN
	WHERE TENDANGNHAP = @p_TENDANGNHAP AND	  MATKHAU = @P_MATKHAU;